---
- name: MOTD
  hosts: yandex
  become: yes
  vars:
    motd_message: "Привет"

  tasks:
    - name: change motd
      ansible.builtin.copy:
        dest: /etc/motd
        content: |
          {{ motd_message }}
        mode: '0755'